baseURL = "https://hugo-from-scratch.netlify.app/"
languageCode = "en-us"
title = "Hugo From Scratch"
paginate = 10 
pygmentsCodeFences = true
pygmentsStyle = "trac"

[permalinks]
    posts = "/:year/:filename"

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1